class PLPageLocator:
    GEARUP_NAV = "(//li[@class='sub'])[2]"
    SMARTSTYLE_NAV = "//ul[@data-type='horizontal-nav']/li/a[contains(.,'Smart Style')]"
    RUNNING_SUBNAV = "//ul[@data-type='horizontal-nav']/li/ul/li/ul/li/a[contains(.,'Running')]"
    SMARTWATCH_SUBNAV = "(//a[contains(.,'Smart Watches')])[1]"
    SOR_BY_FILTER = "//span[@class='bv_mainselect']"
    SORT_ATOZ = "//a[contains(.,' Alphabetically, A-Z')]"
    SORT_RUNNING_PRODUCTS_LIST = "//a[contains(.,'Nurvv Runn Smart Insoles')]"
    BRAND_CHECKBOX = "(//ul[@class='check']/li)[2]"
    BRAND_LIST_TEXT = "(//span[@class='small'])[1]"
    MINIMUM_PRICE = "//input[@id='min']"
    MAXIMUM_PRICE = "//input[@id='max']"
    PRODUCT_PRICE_LIST = "//div[@class='static']/p[@class='price']"
    LIST_VIEW_BTN = "//i[@class='icon-view-list']"
    COLLECTION_LIST = "//ul[@class='l4cl list']"
    GRID_VIEW_BTN = "//i[@class='icon-view-grid']"
    COLLECTION_GRID = "//ul[@class='l4cl']"
    CURRENT_FILTER_TEXT = "//span[contains(.,'Your current filters')]"
    REMOVE_ALL_FILTERS = "//a[@class='remove-all']"
    TECH_ESSENTIAL_NAV = "//ul[@data-type='horizontal-nav']/li/a[contains(.,'Tech Essentials')]"
    APPLE_WATCH_NAV = "//ul[@data-type='horizontal-nav']/li/ul/li/ul/li/a[contains(.,'Apple Watch Band')]"
    INSTOCK_CHECKBOX = "//ul[@class='check']/li/label[@class='strong']"
    LAST_STOCK_PRODUCT = "(//span[text()='Last stock!'])[1]"
    TOTAL_PRODUCTS_COUNT = "//main[@id='content']/div/div/div/ul/li"
