class RegPageLoc:
    SIGNIN_BTN = "//a[@class=\"toggle mobile-hide\"]"
    LOGIN_EMAIL_ADDRESS = "//input[@id='login_email_address']"
    LOGIN_PASSWORD = "//input[@id='login_password']"
    LOGIN_BTN = "(//p[@class='submit form-group'])[1]"
    CREATE_ACCOUNT_BTN = "(//a[text()='Create account'])[1]"
    FIRST_NAME = "//input[@id=\"firstName\"]"
    LAST_NAME = "//input[@id=\"lastName\"]"
    EMAIL_ADDRESS = "//input[@id=\"email_address\"]"
    NEW_PASSWORD = "//input[@id=\"password\"]"
    CREATE_ACCOUNT_SUBMIT_BTN = "//button[contains(.,\"Create account\")]"
